name: Caramel - API Automation Tests

on:
  push:
  schedule:
    - cron: '0 12 * * 1-5'
  workflow_dispatch:
      inputs:
        env-selector:
          description: Run environment (set env to run with qa - staging - dev - qa2)
          required: true
          type: choice
          options:
            - --env environmentName=qa
            - --env environmentName=staging
            - --env environmentName=dev
            - --env environmentName=qa2
            - --env environmentName=uat          
        specs:
          description: Run specs
          required: true
          type: choice
          options: 
            - --spec 'cypress/e2e/API/caramel/*.cy.js'
            - --spec 'cypress/e2e/API/partners/**/*.cy.js'
            - --spec 'cypress/e2e/API/*/*.cy.js' 
            
    
jobs:
  cypress-run-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run API Test
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run --env environmentName=qa --spec 'cypress/e2e/API/caramel/*.cy.js'
          browser: chrome
          record: false

  api-core-schedule-qa:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run API Test
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run --env environmentName=qa --spec 'cypress/e2e/API/caramel/*.cy.js'
          browser: chrome
          record: false

  api-core-schedule-stg:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run API Test
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run --env environmentName=staging --spec 'cypress/e2e/API/caramel/*.cy.js'
          browser: chrome
          record: false

  api-core-schedule-dev:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run API Test
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run --env environmentName=dev --spec 'cypress/e2e/API/caramel/*.cy.js'
          browser: chrome
          record: false

  api-partners-schedule-stg:
      runs-on: ubuntu-latest
      if: github.event_name == 'schedule'
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Run API Test
          uses: cypress-io/github-action@v5
          with:
            command: npx cypress run --env environmentName=qa --spec 'cypress/e2e/API/partners/**/*.cy.js'
            browser: chrome
            record: false          

  cypress-api-workflow_dispatch:
      runs-on: ubuntu-latest
      if: github.event_name == 'workflow_dispatch'
      steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Run API tests on workflow trigger
            uses: cypress-io/github-action@v5
            with:
              command: npx cypress run ${{ inputs.env-selector }} ${{ inputs.specs }}
              browser: chrome
              record: false
  

